checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableImmutableCache: false

enableImmutableInstalls: false

globalFolder: /tmp/yarnCache

npmPublishAccess: public

packageExtensions:
  "@swc-node/sourcemap-support@*":
    dependencies:
      tslib: "*"
  css@*:
    dependencies:
      fs: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  dynamodb-toolbox@*:
    dependencies:
      "@aws-sdk/util-dynamodb": "*"
  express@*:
    dependencies:
      ejs: "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
